### ISSUE TITLE
The wake from the sleep would cause the reboot. Do you have the same issue?

### ISSUE THREAD

**Issue by sxunix** [Xboarder56/nuc11btm-tosh#1]
The wake from the sleep would cause the reboot. Do you have the same issue?

**Comment by Xboarder56** [comment]
I didn’t have that issue with mine, how long was it in sleep mode for?  Also verify your sleep settings in the bios.

**Comment by sxunix** [comment]
I found the root cause. It is because of the IGPU. I disabled it in the BIOS. Then the wake from the sleep is working now.

**Comment by sxunix** [comment]
By the way, the CPU temperature and fans speed cannot be read by the iStat. Is there any plan to enhance the part? Thanks a lot.

**Comment by Xboarder56** [comment]
Yeah, however I believe that’s no longer needed because i’m doing it via a boot argument. you mind making a pull request with the edited file?

I’ll merge it into the main branch.


in regards to the fans it would be cool to see if they can work. I’m worried it’s because the cpu requires that it be spoofed to boot up.

**Comment by Xboarder56** [comment]
I was able to get CPU temp monitoring working in iStats using FakeSMC3 however this broke the 6800 temp monitoring so still looking at this.

**Comment by Xboarder56** [comment]
I left the latest EFI on overnight and didn't experience any reboots. I have pushed a fix for the sensors working via iStats.
![iStats Sensor Screenshot NUC11BTMi9](https://user-images.githubusercontent.com/967563/178794211-3c2d2f36-1610-430a-a241-bda566a7f23c.png)

**Comment by leedashone** [comment]
Same as me. any sleep cause reboot.
I just disable sleep.

**Comment by sxunix** [comment]
I fixed the issue of the i225-LM and sleep issue. Now the only left unwork parts are as follows.
1. The IGPU
2. The hotplug of TB4

**Comment by Xboarder56** [comment]
@sxunix mind making a pull request with the changes for sleep and nic?

**Comment by sxunix** [comment]
> @sxunix mind making a pull request with the changes for sleep and nic?

For the sleep issue, please set the first display card as PCIE in the bios. There no needs to change anything.

**Comment by Xboarder56** [comment]
@sxunix how did you solve the nic/lan?

**Comment by sxunix** [comment]
> @sxunix how did you solve the nic/lan?

It needs to add two APCI files, which are for the TB4 activation. It seems the Lan is using TB bridge.

**Comment by Xboarder56** [comment]
Mind sharing the files?

**Comment by sxunix** [comment]
> Mind sharing the files?
[NUC11_TB4.zip](https://github.com/Xboarder56/nuc11btm-tosh/files/10367879/NUC11_TB4.zip)
No problem, please add these two files in the ACPI, then the lan is working.
