### ISSUE TITLE
Do I miss anything?  Thanks

### ISSUE THREAD

**Issue by leedashone** [Xboarder56/nuc11btm-tosh#2]
Thanks for your project.  I try use it, but fail.  Do I miss anything? 

--------------------------------
My System Config
--------------------------------
Model: NUC11BTMi7  
MB: NUC11DBBi 
CPU: i7-11700B
GPU: AMD Radeon RX 6600
Wireless: Intel AX210 (orderd a BCM94360NG but still shipping)
RAM: 64G (UMAX D4-3200-32G-2048x8-S x 2)
SSD:  2TB+2TB, UMAX M.2 64X4 2TB T,,   JAJPR600M2048C

--------------------------------
My Install Step
--------------------------------
0. Use my mac
1. Download macOS 12.5.1, put "Install macOS Monterey.app" in Applications folder.
2. Format a 32G USB stick with volume name: ROM
3. sudo /Applications/Install\ macOS\ Monterey.app/Contents/Resources/createinstallmedia --volume /Volumes/ROM   
   The bootable USB stick is ready 
4. Change to NUC11 (Windows 11 installed)
5. Download your EFI folder from github, unzip it on desktop
6. Use GenSMBIOS with product name: MacPro7,1
    get my Serial,mlb,uuid,rom...... etc
7. Use ProperTree modify the config.plist (from you EFI folder) with above info.
8. Use Partition Magic give the USB stick EFI partition a driver letter
9. Run Explorer++ with administrator,, delete the origion EFI folder,
    copy the download+modifyed EFI folder into USB disk.
9. boot NUC11 from USB
-------------------------------
After select "Install Monterey", Screen show an Apple Logo and progress bar ..... 
about 30%,, system hang, A error message say "please contact Apple for support"

Do I miss anything?    Thanks again!

PS:  I think NUC11BTMi9  & NUC11BTMi7  is almost same,, and RX6800/6600 also similar...
       But the EFI just don't work on my config...  :..(

**Comment by Xboarder56** [comment]
try using hack n tool on another mac to build the flash drive and copy the EFI folder.

**Comment by leedashone** [comment]
Thanks for help
After move all jobs to macbook,, I have a step forward.
Now I can boot from USB , select Install, use disk utility to erase target disk,, then continue install...
However,, about at 60% （12 mins left） , installer go unlimited reboot loop.
(Reboot....show apple logo... show error message.... reboot ....)

The error message:

**OCS: No schema for SerialInit at 6 index, context ＜Debug＞!
OCS: No schema for AllowNvramReset at 0 index, context ＜Security＞!
OCS: No schema for AllowToggleSip at 2 index, context ＜Security＞ !**

Any Suggest?

PS: I tryed put NvramReset.efi and ToggleSip.efi into driver folder,
      it's no help.  The reboot loop will stop but system hang.

**Comment by leedashone** [comment]
After check the error log, I found my system crash at disk system.
And .... It's work now!  
My mistake is I am not use APFS to erase disk.
Thanks for help.
